subroutine read_iseed(seedval,pimc,IN_ISEED)
!subroutine read_iseed(sys,IN_ISEED)
    !Description:
    !!@ details
    !> Subroutine read_iseed reads in the seed for the random number generator
    !> and then uses it to initialise the random number generator.  The seed
    !> is generated using /dev/urandom and the value is saved to disk.
    !
    ! initialise mersenee-twistor random number generator
    !
    ! Try using /dev/urandom to get a random number.
    ! /dev/urandom stores random numbers generated by analog sources of randomness
    ! such as hard disk timings, keystroke inputs, mouse movements, etc. It saves
    ! these things and makes a pool of random numbers.
    ! This can fail if /dev/urandom's pool of random numbers is depleted.
    ! If it does you'll probably get the same number over and over again.
    ! If you're worried your numbers aren't random enough,
    ! use /dev/random instead. This will just refuse to spit out a random number
    ! if it's pool of random numbers has run out.
    !
    !\param[in] sys The molsysdat object
    !\param[in] IN_ISEED The relative path to the file where the seed value is saved

    !use molecule_specs
    !use mt19937
    use prng
    use seed
    use pimc_structures

    type (pimc_par) :: pimc
    type (mod_seed), intent(inout) :: seedval
    !type (molsysdat) :: sys
    character(len=80) :: IN_ISEED
    integer :: i
    logical :: file_exists
    
    if (pimc%Restart == 'n' .OR. 's') then
       call system('od -vAn -N4 -td4 < /dev/urandom > '//trim(IN_ISEED))
       open(unit=7,file=trim(IN_ISEED),status='old')
       read(7,*) i
       close(7)
       seedval%seedvalue = abs(i)
       !sys%iseed = abs(i)
       !seedval%seedvalue = 558085479 !only enable for debugging
       print *, '                 Initial SEED:', seedval%seedvalue
    
    else if (pimc%Restart == 'y') then
       ! check whether the file exists first
       inquire(file=adjustl(trim(pimc%resume)), exist = file_exists)
       if (file_exists) then
          open(unit=599,file=adjustl(trim(pimc%resume)),status='old',action='read')
          read(599,*) seedval%seedvalue
          close(unit=599)
          print *, 'Resuming pimc using seed:', seedval%seedvalue
       else
          print *, ' no checkpoint file found from the previous job'
          call exit(1)
       endif
    else
       print *, 'Error: no restart command detected!'
       call exit(1)
    endif
   
    ! init_genrand() is for mt19937
    !call init_genrand(sys%iseed)
    !do i = 1,5
    !print *,'seedval%seedvalue', seedval%seedvalue, 'first rand ',genrand_real(seedval%seedvalue)
    !end do
    !call exit(1)
    return
end
